In [1]:
import numpy as np 

In [2]:
### Creating the first array

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1d array: ", arr_1d)

1d array:  [1 2 3 4 5]


In [4]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array: ", arr_2d)

2d array:  [[1 2 3]
 [4 5 6]]


In [6]:
### List vs array

In [8]:
list = [1,2,3]
print("list multiplication is: ", list * 2)

array = np.array([1,2,3])
print("array multiplication is: ", array * 2)

list multiplication is:  [1, 2, 3, 1, 2, 3]
array multiplication is:  [2 4 6]


### Creating Array from Scratch

In [10]:
zeros = np.zeros((3,4))
print("Zeros are: \n", zeros)

ones = np.ones((2,3))
print("ones arrays: \n", ones)

Zeros are: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones arrays: 
 [[1. 1. 1.]
 [1. 1. 1.]]


### Constants array printing 

In [12]:
full = np.full((2,2),4)
print("full arrays: \n", full)

full arrays: 
 [[4 4]
 [4 4]]


In [13]:
random = np.random.random((2,3))
print("random array: \n", random)

random array: 
 [[0.56046777 0.80701941 0.42445852]
 [0.76978683 0.82290081 0.41751664]]


In [14]:
sequence = np.arange(0,10,2)
print("sequence is: \n",sequence)

sequence is: 
 [0 2 4 6 8]


### Vectors , matrix and Tensors

In [19]:
vector = np.array([1,2,3])
print("vectors: ", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensors: \n", tensor)

vectors:  [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensors: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
arr = np.array([[1,2,3], [4,5,6]])
print("shape: ", arr.shape)
print("Dimenstion ", arr.ndim)
print("size: ", arr.size)
print("Dtype: ", arr.dtype)


shape:  (2, 3)
Dimenstion  2
size:  6
Dtype:  int64
